LPS-194204 | master
brookedalton/liferay-portal pull request #295
Opened 2023-08-30 23:00 UTC by allen-nagtalon

https://liferay.atlassian.net/browse/LPS-194204

2023-08-30 23:00 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-08-31 18:20 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +	@priority = 3
Hey! Just commenting for reference but can you add a description here? Thanks!

2023-08-31 18:20 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +		task ("When the user is signed out") {
Combine with task below please

2023-08-31 18:20 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +		task ("When the user is signed out") {
Combine this one also

2023-08-31 21:19 UTC, brookedalton commented
ci:test:sf

2023-08-31 21:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7214/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7214/jenkins-report.html">here</a>.</b></p>

2023-08-31 21:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1a64811dd0c60e1d2e5f8c69e96572dad4fb23f9">1a64811dd0c60e1d2e5f8c69e96572dad4fb23f9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/allen-nagtalon/liferay-portal/tree/LPS-194204">LPS-194204</a><br/>Branch GIT ID: <a href="https://github.com/allen-nagtalon/liferay-portal/commit/ca6e7d6eb0bc335d2c817f25e6fae125dfd96773">ca6e7d6eb0bc335d2c817f25e6fae125dfd96773</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7214/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7214/jenkins-report.html">here</a>.</h5></details></html>

2023-08-31 21:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7214/">test-portal-source-format#7214</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7214/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/brookedalton/liferay-portal/pull/295">brookedalton#295</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2416770935">[master] ci:test:sf - allen-nagtalon &gt; brookedalton - PR#295 - 2023-08-31[14:19:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/26839/">publish-testray-report#26839</a><br/></div></div>

2023-08-31 23:29 UTC, joshchong requested changes
Thanks @allen-nagtalon! This is looking good for the most part besides some minor requested changes. let me know if you have any questions.

2023-08-31 23:29 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +		task ("Given that the embedded search bar in the header is configured as invisible") {
no need to use the given, when, then verbiage for our tests. lean towards writing tasks like high level steps and assertions. For example, this one can be reworded to: `Configure the embedded header search bar to be invisible`

2023-08-31 23:29 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +		task ("Then the search bar should be visible on the search/edit page, but not visible on the home page") {
there's a lot of assertions happening here that are significant enough to be separated into separate tasks. it's ok if a task just has a single assertion function in it.

example:
- Assert the search bar is visible on the search page
- Assert the search bar is not visible on the view mode of a content page
- Assert the search bar is visible within the edit mode of a content page

2023-08-31 23:29 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +		task ("Then the search bar should be visible on the search/edit page, but not visible on the home page") {
try to do this with the rest of the tasks in the test

2023-08-31 23:29 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +		task ("Given the user is signed out, then the search bar should not be present on the home page and the search page") {
another example:
- Sign out and assert the search bar is not visible on the view mode of a content page
- and that it is also not visible on the search page

2023-08-31 23:29 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +
can you also assert that the "This search bar is not visible..." message is not present as well. I forgot to put that in the ticket steps.

2023-08-31 23:29 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +			AssertElementNotPresent(locator1 = "Search#EMBEDDED_HEADER_SEARCH_BAR");
assert that the "This search bar is not visible.." is not present as well

2023-09-01 00:07 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +		task ("Then the search bar should be visible on the search/edit page, but not visible on the home page") {
My bad on this - I asked for a lot of tasks to be grouped together 😬

2023-09-05 20:20 UTC, allen-nagtalon commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/search/Search.path
> +</tr>
I tested the following tests involving Search#EMBEDDED_SEARCH_BAR and got the following results:

- [PASSED] SearchBarSuggestions#ConfigureBlueprintContributorCharacterThresholds
- [PASSED] ClassicTheme#CanConfigureLookAndFeelSettingsOnSinglePage
- [PASSED] SitesWithPermissions#SitesTemplatePermissionPersistence
- [FAILED] CommerceSearch#SearchBarWidgetSearchProductsByCategory
- [FAILED] TeamExtranet#VerifySearchBarOnPages

2023-09-05 21:47 UTC, joshchong commented
Looks good! Forwarded here with minor changes: https://github.com/brianchandotcom/liferay-portal/pull/140317

2023-09-05 21:47 UTC, joshchong commented
ci:close

2023-09-05 21:47 UTC, closed without merging