LPS-133718
brookedalton/liferay-portal pull request #81
Opened 2021-06-22 02:16 UTC by brookedalton

2021-06-22 02:16 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-06-22 02:16 UTC, brookedalton commented
ci:test:search-experiences

2021-06-22 02:18 UTC, brookedalton commented
ci:stop

2021-06-22 15:18 UTC, brookedalton commented
ci:test:search-experiences

2021-06-22 22:38 UTC, brookedalton commented
ci:test:search-experiences:norebase

2021-06-22 22:38 UTC, liferay-continuous-integration commented
The test will run without rebasing..

2021-06-22 22:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search-experiences</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/736/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/736/jenkins-report.html">here</a>.</b></p>

2021-06-23 00:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search-experiences - 6 out of 9 jobs passed in 1 hour 52 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e6c09af76a97bf1fb593b847396d62a3be4e5f00">e6c09af76a97bf1fb593b847396d62a3be4e5f00</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e6c09af76a97bf1fb593b847396d62a3be4e5f00">e6c09af76a97bf1fb593b847396d62a3be4e5f00</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2016">Acceptance Upstream DXP (master) #2016</a></p><details><summary><strong>ci:test:search-experiences - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/736/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465225/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465227/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230000/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465226/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465222/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230001/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465223/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465224/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/736/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465225/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/465225//consoleText">AXIS_VARIABLE=0,label_exp=!master #465225</a><div><p>Please fix <strong>semantic versioning</strong> on <strong><a href="https://github.com/brookedalton/liferay-portal/tree/LPS-133718">brookedalton/LPS-133718</a></strong><pre><code>     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.util                     MINOR      11.3.0     11.3.0     11.4.0     VERSION INCREASE REQUIRED
     [exec] 	&lt;   class      com.liferay.portal.kernel.util.ReleaseInfo
     [exec] 		+   field      RELEASE_7_4_12_BUILD_NUMBER
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   7412
     [exec] 			+   return     int
     [exec] 		+   field      RELEASE_7_4_2_BUILD_NUMBER
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   7402
     [exec] 			+   return     int
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/11.8.0/a56b38f35b5576a870cd9d5d65ca2350db910355/com.liferay.portal.kernel-11.8.0.jar</code></pre></p></div></div></li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at e6c09af76a97bf1fb593b847396d62a3be4e5f00:</strong></summary><ol><li><div><h5><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465227/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/465227//consoleText">AXIS_VARIABLE=0,label_exp=!master #465227</a><div><p>Please fix <strong>semantic versioning</strong> on <strong><a href="https://github.com/brookedalton/liferay-portal/tree/LPS-133718">brookedalton/LPS-133718</a></strong><pre><code>     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.util                     MINOR      11.3.0     11.3.0     11.4.0     VERSION INCREASE REQUIRED
     [exec] 	&lt;   class      com.liferay.portal.kernel.util.ReleaseInfo
     [exec] 		+   field      RELEASE_7_4_12_BUILD_NUMBER
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   7412
     [exec] 			+   return     int
     [exec] 		+   field      RELEASE_7_4_2_BUILD_NUMBER
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   7402
     [exec] 			+   return     int
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/11.8.0/a56b38f35b5576a870cd9d5d65ca2350db910355/com.liferay.portal.kernel-11.8.0.jar</code></pre></p></div></div></li></ol></div></li></ol></details></details></html>

2021-06-23 00:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/736/">test-portal-acceptance-pullrequest(master)#736</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/736/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search-experiences<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/brookedalton/liferay-portal/pull/81">brookedalton#81</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1542108721">[master] ci:test:search-experiences - brookedalton &gt; brookedalton - PR#81 - 2021-06-22[15:39:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/1377/">publish-testray-report#1377</a><br/></div></div>

2021-06-23 21:18 UTC, joshchong requested changes

2021-06-23 21:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchtuning/SearchExperiences.testcase
> +
I think we should actually move all the raw response stuff into its own test. At a functional level, it's logically different enough from the preview score stuff since it is contained within its own modal. Also since the assertions are kinda weird, it would be nice if the test was separate since it could keep that weirdness to itself and not disturb other tests.

2021-06-23 21:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchtuning/SearchExperiences.testcase
> +		}
maybe we can use `FileUtil.read` for this instead of asserting the file name so that the test asserts the content of the file just in case it's empty or something. I think `FileUtil.read` will also fail if the file is not there so it's like two assertions in one.

you'll probably still need to use an if else statement with use of `fail()`. let's try to make the echo and fail messaged more specific, like <assertion phrase> could no be found within <file name> or something

2021-06-23 21:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/macros/SearchExperiences.macro
> +		WebContentNavigator.openWebContentAdmin(siteURLKey = "guest");
Use `WebContentNavigator.openToAddBasicArticle` to be more direct

2021-06-23 21:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/macros/SearchExperiences.macro
> +		PortletEntry.publish();
I don't think we need to actually publish the web content article and assert the content again. just asserting the pasted values in a text box was enough to ensure that copy paste works.

2021-06-23 21:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/macros/SearchExperiences.macro
> +		RobotType.robotTypeShortcut(locator1 = "Ctrl + v");
were you able to see if the poshi paste function works? If so using that function would be preferred.

2021-06-23 21:56 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchtuning/SearchExperiences.testcase
> +
How does `AssertRawResponseCopyAndDownload` sound?

2021-06-23 22:02 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchtuning/SearchExperiences.testcase
> +		}
I don't know where the file is downloaded to in CI and all of the examples I see that use `FileUtil.read` specify the files location

2021-06-23 23:47 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchtuning/SearchExperiences.testcase
> +
Let's go with `ViewPreviewRawResponse`. We should try to use `Assert` in test names that describes a specific state or scenario (like does this thing do this thing, yes or no?) and `View` for tests that just checks a feature in general (we should probably go back and apply this to all of our tests). We can also just say `RawResponse` because even though we are asserting copy and download, the purpose of the test is ensure the raw response feature is working in general.

2021-06-23 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchtuning/SearchExperiences.testcase
> +		}
I think the download location would just be grabbed from the `output.dir.name` property [like what's happening on this line](https://github.com/liferay/liferay-portal/blob/163503b70ba821289952407c3b4bf37f56d3b421/portal-web/test/functional/com/liferay/portalweb/macros/TestCase.macro#L21).

2021-11-23 21:46 UTC, closed without merging